select * from emp;

--EXERCÍCIO 1 CURSOR IMPLÍCITO

VARIABLE  RESULTADO NUMBER;
DECLARE
  V_SAL NUMBER(9,2);
BEGIN
   SELECT SAL INTO V_SAL FROM EMP WHERE DEPTNO = 3;
   :RESULTADO := SQL%ROWCOUNT;
END;
/
PRINT RESULTADO;

-- EXERCÍCIO 2 CURSOR IMPLÍCITO
CREATE TABLE FUNC_MES(
  MES NUMBER(2),
  NAME VARCHAR2(50)
);
VARIABLE  RESULTADO NUMBER;
BEGIN
   FOR EMP_RECORD IN (SELECT * FROM EMP) LOOP
    IF EMP_RECORD.ENAME = 'LISA'
     THEN INSERT INTO FUNC_MES VALUES(1,EMP_RECORD.ENAME);
    END IF;
   END LOOP;
   :RESULTADO := SQL%ROWCOUNT;
END;
/
PRINT RESULTADO;
DROP TABLE FUNC_MES;

-- EXERCÍCIO 3 CURSOR IMPLÍCITO
VARIABLE  RESULTADO NUMBER;
BEGIN
   UPDATE EMP SET DEPTNO = 2 WHERE DEPTNO = 1;
   :RESULTADO := SQL%ROWCOUNT;
END;
/
PRINT RESULTADO;

-- EXERCÍCIO 4 CURSOR IMPLÍCITO
VARIABLE  RESULTADO NUMBER;
BEGIN
   DELETE FROM EMP WHERE ENAME = 'JOHN';
   IF SQL%FOUND
    THEN :RESULTADO := SQL%ROWCOUNT;
  END IF;
END;
/
PRINT RESULTADO;
SELECT * FROM EMP;
-- EXERCÍCIO 5 CURSOR IMPLÍCITO
VARIABLE  RESULTADO NUMBER;
DECLARE
  V_SAL NUMBER(9,2);
BEGIN
   SELECT SAL INTO V_SAL FROM EMP WHERE ENAME = 'HOMER';
   IF SQL%NOTFOUND
    THEN    :RESULTADO := 0;
   ELSE
    :RESULTADO := SQL%ROWCOUNT;
  END IF;
   
END;
/
PRINT RESULTADO;



-- EXERCÍCIO 6 CURSOR EXPLÍCITO
SET SERVEROUTPUT ON
BEGIN
   FOR emp_record IN (SELECT * FROM EMP) LOOP
     IF emp_record.sal < 1500 THEN
       DELETE FROM EMP WHERE (ENAME = EMP_RECORD.ENAME) AND (SAL = EMP_RECORD.SAL) AND (JOB = EMP_RECORD.JOB);
     END IF;
   END LOOP; --implicit close occurs
 END ;
 /
 
 -- EXERCÍCIO 4 CURSOR EXPLÍCITO
 
SET SERVEROUTPUT ON
DECLARE RESULTADO NUMBER(9,2):= 0;
BEGIN
   FOR emp_record IN (SELECT * FROM EMP) LOOP
     RESULTADO := RESULTADO + EMP_RECORD.SAL;
   END LOOP; --implicit close occurs
   DBMS_OUTPUT.PUT_LINE ('TOTAL DOS SALÁRIOS DE EMP: ' || RESULTADO);
 END ;
 /
 
SET SERVEROUTPUT ON
DECLARE
  CURSOR emp_cursor IS
  SELECT ename, deptno 
   FROM emp;
BEGIN 
  FOR emp_record IN emp_cursor LOOP
  --implicit open and implicit fetch occur
  IF emp_record.deptno = 3 THEN
   DBMS_OUTPUT.PUT_LINE ('Funcionário ' || emp_record.ename || ' trabalha no Departamento de Vendas.');
  END IF;
  END LOOP; --implicit close occurs
  END ;
  / 
  
 --EXERCÍCIO 3 CURSOR EXPLÍCITO
 
SET SERVEROUTPUT ON
BEGIN
   FOR emp_record IN (SELECT * FROM EMP) LOOP
     IF emp_record.sal < 1000 THEN
       DBMS_OUTPUT.PUT_LINE ('FUNCIONÁRIO: ' || EMP_RECORD.ENAME);
     END IF;
   END LOOP; --implicit close occurs
 END ;
 /
 
 --EXERCÍCIO 5 CURSOR EXPLÍCITO
SET SERVEROUTPUT ON
DECLARE 
SALARIO_ANTERIOR NUMBER(9,2):= 0;
SALARIO_NOVO NUMBER(9,2):=0 ;
BEGIN
   FOR emp_record IN (SELECT * FROM EMP) LOOP
     SALARIO_ANTERIOR := EMP_RECORD.SAL;
     SALARIO_NOVO := EMP_RECORD.SAL * 1.2;
     UPDATE EMP SET SAL = SAL*1.2 WHERE (ENAME = EMP_RECORD.ENAME) AND (SAL = EMP_RECORD.SAL) AND (JOB = EMP_RECORD.JOB);
     DBMS_OUTPUT.PUT_LINE ('FUNCIONÁRIO: ' || EMP_RECORD.ENAME || '   SALÁRIO ANTERIOR: ' || SALARIO_ANTERIOR || '    SALÁRIO NOVO:' || SALARIO_NOVO);
   END LOOP; --implicit close occurs
   
 END ;
 /
 
 